spring.application.name=Triatlon
server.port=9000

spring.datasource.url=jdbc:mysql://localhost:3306/triatlon
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n 
logging.level.org.hibernate.SQL=debug

#CONFIGURACION DEL CORREO
correo.asunto=Registro exitoso
correo.mensaje=Hola {nombre}, su registro fue exitoso.

#servidor de correo, GMAIL
spring.mail.host=smtp.gmail.com
#puerto seguro 
spring.mail.port=587
#correo desde el que se enviara
spring.mail.username=#ACA SU CORREO
#contrase\u00f1a de aplicacion
spring.mail.password=#CONSIGA SU CLAVE
#activa autenticacion
spring.mail.properties.mail.smtp.auth=true
#activa el cifrado TLS
spring.mail.properties.mail.smtp.starttls.enable=true
#oblica a usar TLS
spring.mail.properties.mail.smtp.starttls.required=true
